In [1]:
import torch

In [2]:
torch.__version__

'2.4.0+cpu'

In [3]:
torch.cuda.is_available()

False

In [4]:
tensor0D = torch.tensor(0)
tensor1D = torch.tensor([1, 2, 3])
tensor2D = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor3D = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

In [ ]:
print(tensor1D.dtype)


torch.int64


In [6]:
tensor1D_32 = tensor1D.to(torch.float32)
print(tensor1D_32.dtype)

torch.float32


In [7]:
print(tensor2D.shape)

torch.Size([2, 3])


In [8]:
print(tensor2D.reshape(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [9]:
tensor2D_transpose = tensor2D.T
print(tensor2D_transpose)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [10]:
print(tensor2D.matmul(tensor2D.T))

tensor([[14, 32],
        [32, 77]])


In [14]:
import torch.nn.functional as F

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2])
b = torch.tensor([0.0])
z = x1 * w1 + b
a = torch.sigmoid(z)
loss = F.binary_cross_entropy(a, y)
print(loss)



tensor(0.0852)
